config/routes.rb
Rails.application.routes.draw do

  require 'resque/server'
  HhParser::Application.routes.draw do
    mount Resque::Server.new, at: "/resque"
  end

  root 'vacancies#index'

  resources :vacancies, only: [:index, :show]
end

app/models/vacancy.rb
class Vacancy < ActiveRecord::Base

  # Если vacancy_id не представлен, то объект не сохранится в базу
  validates :vacancy_id, presence: true

  # Если vacancy_id не уникален, то объект не сохранится в базу
  validates :vacancy_id, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/vacancies_controller.rb
class VacanciesController < ApplicationController

  def index
    @vacancies = Vacancy.all
  end

  def show
    @vacancy = Vacancy.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/vacancies_helper.rb
module VacanciesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HhParser</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/vacancies/index.html.erb
<div class="vacancies">
  <h2>Список вакансий Ruby программиста в Санкт-Петербурге</h2>
  <% @vacancies.each do |vacancy| %>
      <div class="vacancy">
        <p><%= link_to vacancy.name, vacancy_path(vacancy) %></p>
        <p><%= vacancy.short_description.html_safe if vacancy.short_description.present?%></p>
      </div>
  <% end %>
</div>

app/views/vacancies/show.html.erb
<div class="vacancy-details">
  <h2><%= @vacancy.name %></h2>
  <h3>Описание</h3>
  <P><%= @vacancy.description.html_safe %></p>
  <h3>Зарплата</h3>
  <p>
    <%= "от #{@vacancy.salary_from} " if @vacancy.salary_from.present? %>
    <%= "до #{@vacancy.salary_to} " if @vacancy.salary_to.present? %>
    <%= @vacancy.currency if @vacancy.currency.present? %>
    <% unless @vacancy.salary_from.present? || @vacancy.salary_to.present? || @vacancy.currency.present? %>
      <%= 'з/п не указана' %>
    <% end %>
  </p>
  <h3>Ссылка на вакансию</h3>
  <%= link_to @vacancy.link, @vacancy.link %>
  <h3>Компания</h3>
  <%= link_to @vacancy.company_name, @vacancy.company_link %>
</div>